Repository teamleadercrm/ui-icons, pull requests merged in 2020-03, with the labels that each got.

#129 Create workorder medium filled icon
  CHANGELOG.md
  icons/24x24_workorder_filled.svg
Labels: enhancement, ready

#132 Release 0.2.24
  CHANGELOG.md
  package.json
Labels: ready

#136 Team icon 14x14
  CHANGELOG.md
  icons/14x14_team_outline.svg
  package.json
Labels: new icon, ready

#140 Replace team 14x14 outline with edited version
  icons/14x14_team_outline.svg
Labels: enhancement, ready

#143 Maintenance: switch to yarn
  CHANGELOG.md
  README.md
  package.json
  yarn.lock
Labels: enhancement, maintenance, ready

#144 Release 0.2.26
  CHANGELOG.md
  package.json
Labels: ready
