Repository teamleadercrm/ui-icons, pull requests merged in 2021-03, with the labels that each got.

#264 Lock icon outline & filled
  CHANGELOG.md
  icons/14x14_lock_filled.svg
  icons/14x14_lock_outline.svg
  package.json
Labels: enhancement, new icon, ready

#269 Add missing viewBox property
  CHANGELOG.md
  icons/14x14_lock_filled.svg
  icons/14x14_team_outline.svg
  icons/24x24_happy_outline.svg
  icons/24x24_heart_outline.svg
  icons/24x24_hourglass_outline.svg
  icons/24x24_overview_outline.svg
  icons/24x24_pauze_filled.svg
  icons/24x24_play_filled.svg
  icons/24x24_sad_outline.svg
  icons/24x24_warning_outline.svg
Labels: ready

#270 Release 1.0.1
  CHANGELOG.md
  package.json
Labels: ready

#271 Add react 17 as a valid peer dependency
  CHANGELOG.md
  bin/create.js
  package.json
Labels: ready

#275 Add icons - 14x14 outline grab and title
  CHANGELOG.md
  icons/14x14_grab_outline.svg
  icons/14x14_title_outline.svg
  package.json
Labels: new icon
