Repository teamleadercrm/ui-icons, pull requests merged in 2021-04, with the labels that each got.

#279 Add 14x14 play filled icon
  CHANGELOG.md
  icons/14x14_play_filled.svg
  package.json
Labels: enhancement

#282 Feature: Add 14x14_dollar_filled.svg
  CHANGELOG.md
  icons/14x14_dollar_filled.svg
  package.json
Labels: question, ready

#283 Update reviewers to fix dependabot assignments
  .github/dependabot.yml
Labels: maintenance, ready
