Repository teamleadercrm/ui-icons, pull requests merged in 2023-09, with the labels that each got.

#483 Release/2.7.0
  CHANGELOG.md
  icons/24x24_forms_filled.svg
  icons/24x24_forms_outline.svg
  package.json
Labels: new icon

#485 Create tags on bump
  .github/workflows/create-tag.yaml
  package.json
Labels: enhancement

#489 Fix 14x14_percentage_up.svg dimensions
  CHANGELOG.md
  icons/14x14_percentage_up.svg
  package.json
Labels: bug
